

Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint leaves")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Oranges")
Ingredient.create(name: "Brown Sugar")
Ingredient.create(name: "Soda")
Ingredient.create(name: "Tonic")
Ingredient.create(name: "Red Bull")
Ingredient.create(name: "Whisky")
Ingredient.create(name: "Triple Sec")
Ingredient.create(name: "Orange Juice")
Ingredient.create(name: "Limon")
Ingredient.create(name: "Coca-Cola")

Ingredient.create(name: "Red Bull")
Ingredient.create(name: "Whisky")
Ingredient.create(name: "Triple Sec")
Ingredient.create(name: "Orange Juice")
Ingredient.create(name: "Limon")
Ingredient.create(name: "Coca-Cola")
